parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      node8:
        nodeVersion: 8.x
      node10:
        nodeVersion: 10.x
      node11:
        nodeVersion: 11.x
  steps:
  - task: NodeTool@0
    displayName: Use Node
    inputs:
      versionSpec: $(nodeVersion)
      checkLatest: true

  - ${{ if eq(parameters.name, 'Windows') }}:
    - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
      displayName: 'Run CredScan'
      inputs:
        verboseOutput: true
        debugMode: false
      continueOnError: true

  - task: Npm@1
    displayName: npm install
    inputs:
      command: custom
      customCommand: install --unsafe-perms
      verbose: false

  - ${{ if eq(parameters.name, 'Linux') }}:
    - script: |
        cd '$(Build.SourcesDirectory)'

        export npm_package_engines_vscode='^1.19.0'
        node ./node_modules/vscode/bin/install

  - task: Npm@1
    displayName: npm build
    inputs:
      command: custom
      customCommand: run build
      verbose: false

  - task: Npm@1
    displayName: npm test
    inputs:
      command: custom
      verbose: false
      customCommand: test

  - task: Npm@1
    displayName: npm tslint
    inputs:
      command: custom
      verbose: false
      customCommand: 'run tslint'

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
    inputs:
      ignoreDirectories: 'testdata'

  - task: Npm@1
    displayName: npm package
    inputs:
      command: custom
      verbose: false
      customCommand: 'run package -- --packagePath="$(Build.BinariesDirectory)/vscode-node-debug2.vsix"'

  - task: ArchiveFiles@2
    displayName: Archive files
    inputs:
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: drop
      publishLocation: Container
